import Navbar from '@/components/navbar'
import './globals.css'
import { Mali } from 'next/font/google'

const inter = Mali({ subsets: ['latin'], weight: "700" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-black">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  )
}
